/*
 * C ABI around the Lean engine. This is the *only* C in the project.
 *
 *   mathengine_init()              -- initialize the Lean runtime + module (call once)
 *   mathengine_call(const char*)   -- JSON-RPC request in, JSON-RPC response out (read it, then free it)
 *   mathengine_free(const char*)   -- release a response (the last call's; the engine keeps it until then)
 *
 * The engine is a pure function `handleS : Store → String → Store × String`; the session store is
 * held here in a static between calls, so the host (worker, server) stays stateless.
 * Emscripten exports these to JS (see scripts/build-wasm.sh); the native test (c/test.c)
 * exercises the identical call path, so the wasm build only adds the toolchain, not new code.
 */
#include <lean/lean.h>
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#define KEEP EMSCRIPTEN_KEEPALIVE
#else
#define KEEP
#endif

/* Generated by `lake build` from MathEngine.lean / @[export mathengine_handle_state].
 * Since Lean 4.33 (lean4#10625, zero-cost BaseIO) module initializers take no world token and are
 * prefixed with the Lake package name: initialize_<package>_<Module>(builtin). */
extern void lean_initialize_runtime_module(void);
extern lean_object* initialize_mathengine_MathEngine(uint8_t builtin);
extern lean_object* mathengine_handle_state(lean_object* store, lean_object* request);

static lean_object* g_store = NULL;   /* MathEngine.Store; the empty list is the scalar 0 */
static lean_object* g_last = NULL;    /* the reply of the last call, whose characters the caller holds until mathengine_free */

KEEP int mathengine_init(void) {
  lean_initialize_runtime_module();
  lean_object* res = initialize_mathengine_MathEngine(1 /* builtin */);
  if (lean_io_result_is_error(res)) { lean_io_result_show_error(res); lean_dec(res); return 1; }
  lean_dec_ref(res);
  lean_io_mark_end_initialization();
  g_store = lean_box(0);
  return 0;
}

/* The reply is the Lean string itself, not a copy: the caller reads it (the worker turns it into a
 * JavaScript string) and then frees it, which releases the Lean object. A call before init, or after
 * a call that trapped (the store is gone with it), answers with an error rather than dereferencing
 * nothing; that literal is not freed. */
KEEP const char* mathengine_call(const char* request) {
  if (g_store == NULL) return "{\"jsonrpc\":\"2.0\",\"id\":null,\"error\":{\"code\":-32000,\"message\":\"the engine has no session store: it is not initialized, or a call crashed\"}}";
  lean_object* req = lean_mk_string(request);                 /* owned */
  lean_object* store = g_store;
  g_store = NULL;                                             /* taken by the call: a trap inside it leaves nothing dangling */
  lean_object* pair = mathengine_handle_state(store, req);    /* consumes both, returns owned (store, string) */
  store = lean_ctor_get(pair, 0);
  lean_object* res = lean_ctor_get(pair, 1);
  lean_inc(store); lean_inc(res);
  lean_dec(pair);
  g_store = store;
  g_last = res;
  return lean_string_cstr(res);
}

KEEP void mathengine_free(const char* s) {
  if (g_last != NULL && s == lean_string_cstr(g_last)) { lean_dec(g_last); g_last = NULL; }
}
