#!/usr/bin/env python3
"""The symbol table a static wasm build of Lean uses in place of dlsym.

Lean's IR interpreter switches to compiled code by looking up a declaration's mangled C name in the
running binary (`lookup_symbol_in_cur_exe`, `src/library/ir_interpreter.cpp`), and module
initializers are found the same way. Natively that is `dlsym`; a statically linked Emscripten binary
has no symbol table at runtime (Lean's own wasm recipe links with MAIN_MODULE=1/EXPORT_ALL for it,
which makes every lookup a slow JavaScript search). This script writes one in C instead:

  usage: lean-wasm-symtab.py OUT.c NM_OUTPUT C_FILE_LIST     (a file naming the C files, one per line)

The prototypes come from the Lean-emitted C itself (every file declares, one per line, each function
and constant it defines or uses), so each table entry takes the address of a correctly typed
declaration and wasm-ld never sees a signature mismatch. Only symbols the linked objects define
(`llvm-nm` output, global T/D/B/R) are kept. Entries are keyed by the 64-bit FNV-1a hash of the name
rather than the name, which keeps megabytes of mangled names out of the binary; a hash collision
between two table entries fails the build.
"""
import re
import sys

FUN = re.compile(r'^(?:LEAN_EXPORT |extern )?((?:[A-Za-z_][A-Za-z0-9_]*[ *]+)+?)([A-Za-z_][A-Za-z0-9_]*)\(([^()]*)\);$')
# Lean's forward declarations name types only: `lean_object*`, `uint8_t`, `size_t`, `double`, ...
ARG_TYPE = re.compile(r'^(?:const )?(?:[A-Za-z_][A-Za-z0-9_]*_t|lean_object|lean_obj_arg|b_lean_obj_arg|lean_obj_res|double|float|char|int|unsigned|void) ?\**(?: ?[A-Za-z_][A-Za-z0-9_]*)?$')
VAR = re.compile(r'^(?:LEAN_EXPORT |extern )?((?:lean_object|uint8_t|uint16_t|uint32_t|uint64_t|size_t|double|float) ?\*?) ?([A-Za-z_][A-Za-z0-9_]*);$')


def fnv1a64(s: bytes) -> int:
    h = 0xcbf29ce484222325
    for b in s:
        h ^= b
        h = (h * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return h


def main() -> None:
    out, nm_file, c_list = sys.argv[1:]
    c_files = [l.strip() for l in open(c_list, encoding='utf8') if l.strip()]
    defined = set()
    for line in open(nm_file, encoding='utf8', errors='replace'):
        parts = line.split()
        if len(parts) >= 2 and parts[-2] in ('T', 'D', 'B', 'R'):
            defined.add(parts[-1])

    funs: dict[str, str] = {}
    vars_: dict[str, str] = {}
    for path in c_files:
        for line in open(path, encoding='utf8', errors='replace'):
            if not line or line[0] in ' \t#/{}' or line.startswith('static'):
                continue
            line = line.rstrip('\n')
            m = FUN.match(line)
            if m:
                ret, name, args = m.group(1).strip(), m.group(2), m.group(3)
                if ret.split()[0] in ('return', 'else', 'goto', 'case') or not all(
                        ARG_TYPE.match(a.strip()) for a in args.split(',') if a.strip()):
                    continue   # a statement (`return initialize_X(builtin);`), not a declaration
                if name in defined and name not in funs:
                    funs[name] = f'{ret} {name}({args});'
                continue
            m = VAR.match(line)
            if m:
                ty, name = m.group(1).strip(), m.group(2)
                if name in defined and name not in vars_ and name not in funs:
                    vars_[name] = f'extern {ty} {name};'

    entries = sorted((fnv1a64(n.encode()), n) for n in list(funs) + list(vars_))
    for (h1, n1), (h2, n2) in zip(entries, entries[1:]):
        if h1 == h2:
            sys.exit(f'lean-wasm-symtab: hash collision between {n1} and {n2}')

    with open(out, 'w', encoding='utf8') as f:
        f.write('// Generated by scripts/lean-wasm-symtab.py. Do not edit.\n')
        f.write('#include <lean/lean.h>\n#include <stdint.h>\n#include <stddef.h>\n')
        f.write('#pragma clang diagnostic ignored "-Wincompatible-library-redeclaration"\n')
        f.write('#pragma clang diagnostic ignored "-Wbuiltin-requires-header"\n')
        for decl in funs.values():
            f.write(decl + '\n')
        for decl in vars_.values():
            f.write(decl + '\n')
        f.write(f'static const uint64_t lean_wasm_sym_hash[{len(entries)}] = {{\n')
        f.writelines(f'0x{h:016x}ull,\n' for h, _ in entries)
        f.write('};\n')
        f.write(f'static void * const lean_wasm_sym_addr[{len(entries)}] = {{\n')
        f.writelines(f'(void *)&{n},\n' for _, n in entries)
        f.write('};\n')
        f.write(f'''
LEAN_EXPORT void * lean_wasm_lookup_symbol(char const * s) {{
    uint64_t h = 0xcbf29ce484222325ull;
    for (; *s; ++s) {{ h ^= (unsigned char)*s; h *= 0x100000001b3ull; }}
    size_t lo = 0, hi = {len(entries)};
    while (lo < hi) {{
        size_t mid = lo + (hi - lo) / 2;
        if (lean_wasm_sym_hash[mid] < h) lo = mid + 1; else hi = mid;
    }}
    return lo < {len(entries)} && lean_wasm_sym_hash[lo] == h ? lean_wasm_sym_addr[lo] : NULL;
}}
''')
    print(f'lean-wasm-symtab: {len(funs)} functions, {len(vars_)} constants', file=sys.stderr)


if __name__ == '__main__':
    main()
